# Data Preprocessing Template

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [6]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
#index locatation[행 범위 , 열 범위]의 값들을 특징 행렬로
y = dataset.iloc[:, -1].values

In [7]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# 대치 SimpleImputer라는 클래스를 활용해 객체 생성, np.nan (not a number check ) 후 교체(대치) 전략을 평균으로
imputer.fit(X[:, 1:3]) #fit가 특징 행렬을 탐색하는데 문자열 파트는 에러를 발생시키므로 범위 나누기 - 탐색
X[:, 1:3] = imputer.transform(X[:, 1:3]) # 실질적 변환 후 업데이트

In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

## Encoding the Independent Variable

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# 두 가지의 인자를 포함하는데 첫 번째 인자는 뭘 할건지, 두번째는 방법, 세번째는 범위, 두번 째 인자에서는 나머지 열의 처리여부
# ColumnTransformer가 조정과 변환기능 과정을 한 번에 처리해줘서 바로 처리 가능
X = np.array(ct.fit_transform(X)) # 반환이 numpy로 안돼서 직접 처리

In [11]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Encoding the Dependent Variable

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) # 그냥 결과를 표시하면 돼서 np로 바꿀 필요 없음


In [14]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splittig the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
# 네 개를 반환
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
# argument로 특징 행렬과 종속 벡터를 인자로, 훈련 세트는 80퍼센트의 관측값 테스트 세트는 20% 관측값 권장